apiVersion: apps/v1
kind: Deployment
metadata:
  name: smartrh-frontend
  namespace: smartrh

spec:
  replicas: 2

  selector:
    matchLabels:
      app: smartrh-frontend

  template:
    metadata:
      labels:
        app: smartrh-frontend

    spec:
      containers:
        - name: frontend

          # ✅ IMAGE CORRECTE (containerd)
          image: salma217/smartrh-frontend:latest   #docker.io/library/smarthr-frontend:latest

          # ✅ IMPORTANT POUR TON CLUSTER
          imagePullPolicy: IfNotPresent

          env:
            - name: REACT_APP_API_URL
              value: "http://smartrh-backend-service:5000"

          ports:
            - containerPort: 80
